undef(resolve) adding Hoa namespace to resolve to avoid conflict
hoaproject/Protocol pull request #22
Opened 2017-08-04 20:43 UTC by Grummfy

related to https://github.com/hoaproject/Central/issues/61
once we have discuted about it, I will get back on other repository depending on this function.

note with php 5.6+ we can use ```use function \Hoa\resolve``` in the import part

2017-08-07 08:50 UTC, vonglasow commented
Can you complete also the README please ?

2017-08-07 08:55 UTC, Hywan requested changes
I guess it's cool with this modification. Thoughts?

2017-08-07 08:55 UTC, Hywan commented on Wrapper.php
> -namespace
Remove this.

2017-08-07 08:55 UTC, Hywan commented on Test/Unit/Wrapper.php
> -            resolve('hoa://Test/Vfs/Bar/' . $child . '?type=file');
`Hoa\Protocol\Protocol::getInstance()->resolve(…)` is better.

2017-08-07 08:55 UTC, Hywan commented on Bin/Resolve.php
> -        $resolved = resolve($path, $exists, $unfold);
`Hoa\Protocol\Protocol::getInstance()->resolve(…)` is better.

2017-08-07 20:54 UTC, Grummfy commented
here it is

2017-08-08 07:10 UTC, Grummfy commented
Yes, because less bc break is good.
No, because it break my laravel app ;)

But, I can wait. What do we need for breaking php compatibility?
Did I update other library to remove it?

2017-08-08 07:14 UTC, Hywan commented
We must implement `Hoa\Option`, and then use it for all new libraries. With `Hoa\Option`, we will introduce BC, and thus we will upgrade to PHP 7. I can focus my work on `Hoa\Option`, then use it in `Hoa\Consistency`, do a new major release, and use it in `Hoa\Protocol` with a new major release. Thoughts?

2017-08-08 07:26 UTC, Grummfy commented
OK.

2017-08-30 12:26 UTC, merged

2018-03-20 05:54 UTC, drewsymo commented
Hey all! 

We've just implemented the Hoa\Ruler package in Laravel and this is causing some serious headaches for us as we have other packages using Laravel's `resolve` function internally.

Is there any update on when this will be released? Is it safe to just use `dev-master` for the protocol package for now?

2019-08-07 20:21 UTC, jaroslavas commented
Hey guys, when will you release this? Your libraries are still unusable with Laravel because of this resolve function!